# Generated by Django 5.1.5 on 2025-01-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images'),
        ),
    ]
