# Generated by Django 5.1.4 on 2025-01-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_order_product_alter_caritem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='current_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_courier', to='food.order'),
        ),
    ]
