# Generated by Django 5.1.4 on 2025-01-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_product_store_alter_reviewstore_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='food.product'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='food.store'),
        ),
    ]
