# Generated by Django 5.1.5 on 2025-01-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_product_store_alter_reviewstore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingcourier',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_for_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caritem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='food.product'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='food.store'),
        ),
        migrations.AlterField(
            model_name='ratingcourier',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
