# Generated by Django 5.1.5 on 2025-01-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_ratingcourier_client_alter_caritem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgers',
            name='burger_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
