# Generated by Django 5.1.5 on 2025-01-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_burgers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgers',
            name='burgers_image',
            field=models.ImageField(blank=True, null=True, upload_to='burger_images'),
        ),
    ]
