# Generated by Django 5.1.4 on 2025-01-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_caritem_product_alter_contactinfo_store'),
        ('food', '0011_alter_burgers_burgers_image'),
    ]

    operations = [
    ]
