# Generated by Django 5.1.4 on 2025-01-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_merge_20250121_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burgers',
        ),
    ]
