# Generated by Django 5.1.5 on 2025-01-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.productcombo'),
        ),
    ]
